// Auto-generated by scripts/sync-vpc-bindings.mjs from wrangler.jsonc.
// Do not edit by hand — your changes will be overwritten on the next
// `npm run build`. To add or remove a binding, edit wrangler.jsonc.

import type { VpcBinding } from "./vpc";

export const VPC_BINDINGS: VpcBinding[] = [];
